name: dschaei_pi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  modal_bottom_sheet: ^3.0.0
  flutter_launcher_icons: "^0.11.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/applogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/details/
    - assets/backgrounds/
    - assets/graphics/

